application: speek-up
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /bundles
  static_dir: web/bundles

- url: /robots.txt
  static_files: web/robots.txt
  upload: web/robots.txt

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
 
- url: /clear_cache
  script: web/clear_cache.php
 
- url: /.*
  script: web/app.php
  
env_variables:
  GCS_BUCKET_NAME: speek-up
  CACHE_DIR: "gs://#default#/symfony/cache"
  LOG_DIR: "gs://#default#/symfony/log"
  
skip_files:
  - (.*/)?Tests\/Fixtures\/(.*)
